Net Project/Cotizaciones/Cotizaciones/Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Cotizaciones.Models;
using System.Web.Security;

namespace Cotizaciones.Controllers
{
    [Authorize(Roles = "authorized-user")]
    public class DashboardController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        
        public Order fillData(int id)
        {
            var orderQuery = from o in db.Orders.Include("Step") where (o.OrderId.Equals(id)) select o;
            Order order = orderQuery.ToList().ElementAt(0);
            ViewBag.OrderProducts = db.OrderProducts.ToList().Where(op => op.Order.OrderId == order.OrderId);
            ViewBag.StepChanges = order.StepChanges.ToList();
            var stepQuery = from s in db.Steps select s;
            List<Step> steps = stepQuery.ToList();
            Dictionary<int, string> stepNames = new Dictionary<int, string>();
            foreach (Step s in steps)
                stepNames.Add(s.StepId, s.getDisplayName());
            ViewBag.StepNames = stepNames;
            ViewBag.OrderComments = order.OrderComments.ToList();
            return order;
        }
                
        public ActionResult MyOrders(string sortOrder)
        {
            ViewBag.SortOrder = String.IsNullOrEmpty(sortOrder) ? "dateAsc" : sortOrder;
            var orders = from o in db.Orders.Include("Step") select o;
            switch (sortOrder)
            {
                case "dateDesc":
                    orders = orders.OrderByDescending(o => o.DateCreated);
                    break;
                case "identifierDesc":
                    orders = orders.OrderByDescending(o => o.Identifier);
                    break;
                case "identifierAsc":
                    orders = orders.OrderBy(o => o.Identifier);
                    break;
                case "stepDesc":
                    orders = orders.OrderByDescending(o => o.Step.Order);
                    break;
                case "stepAsc":
                    orders = orders.OrderBy(o => o.Step.Order);
                    break;
                case "timeDesc":
                    orders = orders.OrderByDescending(o => o.DateCreated);
                    break;
                case "timeAsc":
                    orders = orders.OrderBy(o => o.DateCreated);
                    break;
                default:
                    orders = orders.OrderBy(o => o.DateCreated);
                    break;
            }
            return View(orders.ToList());
        }

        public ActionResult FillOrder(int id)
        {            
            return View(fillData(id));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult PushOrder(int orderId)
        {
            //User is logged in
            if(!User.Identity.IsAuthenticated || !User.IsInRole("authorized-user"))
            {
                return RedirectToAction("MyOrders");
            }
            var orderQuery = from o in db.Orders.Include("Step") where (o.OrderId.Equals(orderId)) select o;
            Order order = orderQuery.ToList().ElementAt(0);
            //User is responsible for this step
            if(!User.IsInRole(order.Step.Responsible))
            {
                return RedirectToAction("MyOrders");
            }
            //TODO: Check user has properly filled the data corresponding to this step
            //Move to next step, if succesfull, record the change
            Step previousStep = order.Step;
            var stepQuery = from s in db.Steps where (s.Order.Equals(previousStep.Order+1)) select s;
            Step newStep = stepQuery.ToList().ElementAt(0);
            try
            {
                order.Step = newStep;
                db.SaveChanges();
                StepChange stepChange = new StepChange();
                stepChange.DateChanged = DateTime.Now;
                stepChange.PreviousStepId = previousStep.StepId;
                stepChange.NextStepId = newStep.StepId;
                stepChange.User = User.Identity.Name;
                order.StepChanges.Add(stepChange);
                db.SaveChanges();
                Session["pendingOrders"] = orderQuery.ToList().Where(o => User.IsInRole(o.Step.Responsible)).Count();
            }
            catch
            {
                return RedirectToAction("MyOrders");
            }
            return RedirectToAction("MyOrders");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SaveComment(int orderId, string comment)
        {
            //User is logged in
            if (!User.Identity.IsAuthenticated || !User.IsInRole("authorized-user"))
            {
                return RedirectToAction("MyOrders");
            }
            //User is responsible for this step
            Order order = fillData(orderId);
            if (!User.IsInRole(order.Step.Responsible))
            {
                return RedirectToAction("MyOrders");
            }
            //Move to next step, if succesfull, record the change
            try
            {
                OrderComment orderComment = new OrderComment();
                orderComment.Date = DateTime.Now;
                orderComment.Comment = comment;
                orderComment.Step = order.Step;
                orderComment.User = User.Identity.Name;
                order.OrderComments.Add(orderComment);
                db.SaveChanges();
            }
            catch
            {
                return RedirectToAction("FillOrder", new { @id = orderId });
            }
            return RedirectToAction("FillOrder", new { @id = orderId });
        }

    }
}

Net Project/Cotizaciones/Cotizaciones/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Cotizaciones.Models;

namespace Cotizaciones.Controllers
{
    [Authorize(Roles = "authorized-user")]
    public class OrdersController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Orders
        public ActionResult Index(string sortOrder)
        {
            ViewBag.SortOrder = String.IsNullOrEmpty(sortOrder) ? "dateAsc" : sortOrder;
            var orders = from o in db.Orders select o;
            switch (sortOrder)
            {
                case "dateDesc":
                    orders = orders.OrderByDescending(o => o.DateCreated);
                    break;
                case "identifierDesc":
                    orders = orders.OrderByDescending(o => o.Identifier);
                    break;
                case "identifierAsc":
                    orders = orders.OrderBy(o => o.Identifier);
                    break;
                case "projectDesc":
                    orders = orders.OrderByDescending(o => o.Preproject);
                    break;
                case "projectAsc":
                    orders = orders.OrderBy(o => o.Preproject);
                    break;
                default:
                    orders = orders.OrderBy(o => o.DateCreated);
                    break;
            }
            return View(orders);
        }

        // GET: Orders/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = db.Orders.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            ViewBag.StepChanges = order.StepChanges.ToList();
            ViewBag.OrderProducts = db.OrderProducts.ToList().Where(op => op.Order.OrderId == order.OrderId);
            var stepQuery = from s in db.Steps select s;
            List<Step> steps = stepQuery.ToList();
            Dictionary<int, string> stepNames = new Dictionary<int, string>();
            foreach (Step s in steps)
                stepNames.Add(s.StepId, s.getDisplayName());
            ViewBag.StepNames = stepNames;
            ViewBag.OrderComments = order.OrderComments.ToList();
            return View(order);
        }

        // GET: Orders/Create
        [Authorize(Roles = "admin, management, sales-admin")]
        public ActionResult Create()
        {
            ViewBag.Clients = db.Clients.ToList();
            return View();
        }

        // POST: Orders/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin, management, sales-admin")]
        public ActionResult Create([Bind(Include = "OrderId,Identifier,Preproject,RequestDescription,Client")] Order order, int clientId)
        {
            if (ModelState.IsValid)
            {
                if(db.Orders.Select(o => o.Identifier).ToList().Contains(order.Identifier))
                {
                    ModelState.AddModelError("Identifier", "Ya existe una orden con ese identificador");
                    return View();
                }
                order.DateCreated = DateTime.Now;
                var steps = from s in db.Steps where s.Order == 1 select s;
                order.Step = steps.ToList().ElementAt(0);
                var clients = from s in db.Clients where s.ClientId == clientId select s;
                order.Client = clients.ToList().ElementAt(0);
                db.Orders.Add(order);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(order);
        }

        // GET: Orders/Edit/5
        [Authorize(Roles = "admin, management, sales-admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = db.Orders.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            ViewBag.Clients = db.Clients.ToList();
            ViewBag.Products = db.Products.ToList();
            ViewBag.OrderProducts = db.OrderProducts.ToList().Where(op => op.Order.OrderId == order.OrderId);
            return View(order);
        }

        // POST: Orders/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin, management, sales-admin")]
        public ActionResult Edit([Bind(Include = "OrderId,Identifier,Preproject,RequestDescription")] Order order, int clientId)
        {
            if (ModelState.IsValid)
            {
                //db.Entry(order).State = EntityState.Modified;
                Order toModify = db.Orders.Find(order.OrderId);
                toModify.Identifier = order.Identifier;
                toModify.Preproject = order.Preproject;
                toModify.RequestDescription = order.RequestDescription;
                var clients = from s in db.Clients where s.ClientId == clientId select s;
                toModify.Client = clients.ToList().ElementAt(0);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(order);
        }

        // GET: Orders/Delete/5
        [Authorize(Roles = "admin, management, sales-admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = db.Orders.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            return View(order);
        }

        // POST: Orders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin, management, sales-admin")]
        public ActionResult DeleteConfirmed(int id)
        {
            Order order = db.Orders.Find(id);
            db.Orders.Remove(order);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        [HttpPost]
        [Authorize(Roles = "admin, management, sales-admin")]
        public ActionResult AddOrderProduct(int orderId, int productId, string quantity)
        {
            int number = 0;
            Order order = db.Orders.Find(orderId);
            try
            {
                number = int.Parse(quantity);
                Product product = db.Products.Find(productId);
                OrderProduct orderProduct = new OrderProduct();
                orderProduct.Order = order;
                orderProduct.Product = product;
                orderProduct.Quantity = number;
                order.OrderProducts.Add(orderProduct);
                //db.OrderProducts.Add(orderProduct);
                db.SaveChanges();
            }
            catch
            {
                
            }
            ViewBag.Clients = db.Clients.ToList();
            ViewBag.Products = db.Products.ToList();
            ViewBag.OrderProducts = db.OrderProducts.ToList().Where(op => op.Order.OrderId == order.OrderId);
            return RedirectToAction("Edit", new { @id = order.OrderId });
        }

        [Authorize(Roles = "admin, management, sales-admin")]
        public ActionResult DeleteOrderProduct(int orderProductId)
        {
            OrderProduct orderProduct = db.OrderProducts.Find(orderProductId);
            int orderId = orderProduct.Order.OrderId;
            ViewBag.Clients = db.Clients.ToList();
            ViewBag.Products = db.Products.ToList();
            ViewBag.OrderProducts = db.OrderProducts.ToList().Where(op => op.Order.OrderId == orderId);
            db.OrderProducts.Remove(orderProduct);
            db.SaveChanges();
            return RedirectToAction("Edit", new { @id = orderId });
        }
    }
}

Net Project/Cotizaciones/Cotizaciones/Views/Dashboard/FillOrder.cshtml
@model Cotizaciones.Models.Order

@{
    ViewBag.Title = "Llenado de orden";
}

<div class="row">
    <div class="col-md-10">
        <h2>Orden @Model.Identifier - Información a llenar</h2>
    </div>
    <div class="col-md-2" style="float:right; margin-bottom: 5px; margin-top:25px;">
        @using (Html.BeginForm("PushOrder","Dashboard"))
        {
            @Html.AntiForgeryToken()
            <input type="text" hidden="hidden" value="@Model.OrderId" name="orderId" id="orderId" />
            <input type="submit" value="Finalizar paso >>" class="btn btn-success" />
        }
    </div>
</div>

<div class="row">
    <hr />
    <h4>Información a llenar</h4>
    <hr />
    @using (Html.BeginForm("SaveComment", "Dashboard"))
    {
        @Html.AntiForgeryToken()
        <div class="form-horizontal">
            <input type="text" hidden="hidden" value="@Model.OrderId" name="orderId" id="orderId" />
            <div class="form-group">
                <label class="control-label col-md-2">
                    Comentarios
                </label>
                <div class="col-md-10">
                    @foreach (Cotizaciones.Models.OrderComment comment in ViewBag.OrderComments)
                    {
                        if (comment.Step.StepId.Equals(Model.Step.StepId))
                        {
                            <div class="row" style="margin-left:5px">
                                @Html.Raw(string.Format("{0}-{1}: {2}", comment.Date, comment.User, comment.Comment))
                            </div>
                        }
                    }
                    <textarea class="form-control" id="comment" name="comment"></textarea>
                    @Html.ValidationMessageFor(model => model.Identifier, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Guardar comentario" class="btn btn-success" />
                </div>
            </div>
        </div>
    }
</div>

<div class="row">
    <hr />
    <div class="col-md-10">
        <h4>Detalles</h4>
    </div>
    <div class="col-md-2">
        @if (User.IsInRole("admin") || User.IsInRole("management") || User.IsInRole("sales-admin"))
        {
            @Html.ActionLink("Editar Detalles", "Edit", new { id = Model.OrderId }, new { @class = "btn btn-primary" })
        }
    </div>
</div>

<div class="row">
    <hr />
    <div class="col-md-5">
        <h4>Información general</h4>
        @Html.Partial("~/Views/Orders/DetailsPartial.cshtml", Model)
    </div>
    <div class="col-md-5">
        <h4>Productos</h4>
        @Html.Partial("~/Views/Orders/ProductsPartial.cshtml", Model)
    </div>
</div> 

<div class="row">
    <hr />
    <h4>Historial</h4>
    <hr />
    @Html.Partial("~/Views/Orders/HistoryPartial.cshtml")
</div>  

Net Project/Cotizaciones/Cotizaciones/Views/Dashboard/MyOrders.cshtml
@model IEnumerable<Cotizaciones.Models.Order>
@{
    ViewBag.Title = "Mis Órdenes";
}

<h2>Mis Órdenes</h2>

<div class="row">
    <table class="table">
        <tr>
            <th>
                @if (("identifierDesc").Equals(ViewBag.SortOrder))
                {
                    @Html.ActionLink("▼ Identificador", "MyOrders", new { sortOrder = "identifierAsc" })
                }
                else if (("identifierAsc").Equals(ViewBag.SortOrder))
                {
                    @Html.ActionLink("▲ Identificador", "MyOrders", new { sortOrder = "identifierDesc" })
                }
                else
                {
                    @Html.ActionLink("Identificador", "MyOrders", new { sortOrder = "identifierAsc" })
                }
            </th>
            <th>
                @if (("stepDesc").Equals(ViewBag.SortOrder))
                {
                    @Html.ActionLink("▼ Paso Actual", "MyOrders", new { sortOrder = "stepAsc" })
                }
                else if (("stepAsc").Equals(ViewBag.SortOrder))
                {
                    @Html.ActionLink("▲ Paso Actual", "MyOrders", new { sortOrder = "stepDesc" })
                }
                else
                {
                    @Html.ActionLink("Paso Actual", "MyOrders", new { sortOrder = "stepAsc" })
                }
            </th>            
            <th>
                @if (("dateDesc").Equals(ViewBag.SortOrder))
                {
                    @Html.ActionLink("▼ Fecha de creación", "MyOrders", new { sortOrder = "dateAsc" })
                }
                else if (("dateAsc").Equals(ViewBag.SortOrder))
                {
                    @Html.ActionLink("▲ Fecha de creación", "MyOrders", new { sortOrder = "dateDesc" })
                }
                else
                {
                    @Html.ActionLink("Fecha de creación", "MyOrders", new { sortOrder = "dateAsc" })
                }
            </th>
            <th>
                @if (("timeDesc").Equals(ViewBag.SortOrder))
                {
                    @Html.ActionLink("▼ Estado", "MyOrders", new { sortOrder = "timeAsc" })
                }
                else if (("timeAsc").Equals(ViewBag.SortOrder))
                {
                    @Html.ActionLink("▲ Estado", "MyOrders", new { sortOrder = "timeDesc" })
                }
                else
                {
                    @Html.ActionLink("Estado", "MyOrders", new { sortOrder = "timeAsc" })
                }
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            if(User.IsInRole(item.Step.Responsible))
            { 
                <tr>
                    <td>
                        @Html.ActionLink(item.Identifier.ToString(), "Details", "Orders", new { id = item.OrderId }, null)
                    </td>
                    <td>
                        @item.Step.getDisplayName()
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DateCreated)
                    </td>
                    <td>
                        @if (item.onTime().Equals("Atrasado"))
                        {
                            <div style="color:red">Atrasado</div>
                        }
                        else
                        {
                            <div style="color:green">A tiempo</div>
                        }
                    </td>
                    <td>
                        @Html.ActionLink("Atender", "FillOrder", new { @id = item.OrderId }, new { @class = "btn btn-success"})
                    </td>
                </tr>
            }
        }
    </table>
</div>