Net Project/Cotizaciones/Cotizaciones/Models/Order.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Cotizaciones.Models
{
    public class Order
    {
        public int OrderId { get; set; }

        [Required(ErrorMessage = "Este campo es requerido")]
        [Display(Name = "Identificador")]
        public string Identifier { get; set; }

        [Display(Name = "Pre-Proyecto")]
        public Nullable<int> Preproject { get; set; }

        [Display(Name = "Fecha de creación")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
        public DateTime DateCreated { get; set; }

        [Display(Name = "Descripción de la petición")]
        public string RequestDescription { get; set; }

        [Display(Name = "Cliente")]
        public virtual Client Client{ get; set; }

        [Display(Name = "Paso Actual")]
        public virtual Step Step { get; set; }

        public virtual ICollection<StepChange> StepChanges { get; set; }

        public virtual ICollection<OrderComment> OrderComments { get; set; }

        public virtual ICollection<OrderProduct> OrderProducts { get; set; }

        public string onTime()
        {
            var stepChanges = StepChanges.Where(s => s.NextStepId.Equals(Step.StepId));
            if (stepChanges.Count() > 0)
            {
                StepChange stepChange = stepChanges.ElementAt(0);
                if (Step.Tolerance < (DateTime.Now - stepChange.DateChanged).TotalHours)
                    return "Atrasado";
                else
                    return "A tiempo";
            }
            else
            {
                if (Step.Tolerance < (DateTime.Now - DateCreated).TotalHours)
                    return "Atrasado";
                else
                    return "A tiempo";
            }
        }

        public decimal getTotal()
        {
            decimal result = 0;
            foreach(OrderProduct orderProduct in OrderProducts)
            {
                if (orderProduct.Product.ProviderPrice != null)
                    result += (decimal) (orderProduct.Quantity * orderProduct.Product.ProviderPrice);
            }
            return result;
        }
    }
}

Net Project/Cotizaciones/Cotizaciones/Controllers/ClientsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Cotizaciones.Models;

namespace Cotizaciones.Controllers
{
    [Authorize(Roles = "authorized-user")]
    public class ClientsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        
        public ActionResult Index(string sortOrder)
        {
            ViewBag.SortOrder = String.IsNullOrEmpty(sortOrder) ? "nameAsc" : sortOrder;
            var clients = from c in db.Clients select c;
            switch (sortOrder)
            {
                case "nameDesc":
                    clients = clients.OrderByDescending(c => c.Name);
                    break;
                case "categoryDesc":
                    clients = clients.OrderByDescending(c => c.Category);
                    break;
                case "categoryAsc":
                    clients = clients.OrderBy(c => c.Category);
                    break;
                default:
                    clients = clients.OrderBy(c => c.Name);
                    break;
            }
            return View(clients);
        }

        // GET: Clients/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Client client = db.Clients.Find(id);
            if (client == null)
            {
                return HttpNotFound();
            }
            return View(client);
        }

        [Authorize(Roles = "admin, management, sales-admin")]
        // GET: Clients/Create
        public ActionResult Create()
        {
            return View();
        }

        [Authorize(Roles = "admin, management, sales-admin")]
        // POST: Clients/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ClientId,Name,LastName,Company,Address,City,State,Country,Phone,Extension,CellPhone,Email,Category")] Client client)
        {
            if (ModelState.IsValid)
            {
                db.Clients.Add(client);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(client);
        }

        [Authorize(Roles = "admin, management, sales-admin")]
        // GET: Clients/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Client client = db.Clients.Find(id);
            if (client == null)
            {
                return HttpNotFound();
            }
            return View(client);
        }

        [Authorize(Roles = "admin, management, sales-admin")]
        // POST: Clients/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ClientId,Name,LastName,Company,Address,City,State,Country,Phone,Extension,CellPhone,Email,Category")] Client client)
        {
            if (ModelState.IsValid)
            {
                db.Entry(client).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(client);
        }

        [Authorize(Roles = "admin, management, sales-admin")]
        // GET: Clients/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Client client = db.Clients.Find(id);
            if (client == null)
            {
                return HttpNotFound();
            }
            return View(client);
        }

        [Authorize(Roles = "admin, management, sales-admin")]
        // POST: Clients/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Client client = db.Clients.Find(id);
            var orders = from o in db.Orders where o.Client.ClientId == id select o;
            foreach (var order in orders.ToList())
            {
                db.Orders.Remove(order);
            }
            db.Clients.Remove(client);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Net Project/Cotizaciones/Cotizaciones/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Cotizaciones.Models;

namespace Cotizaciones.Controllers
{
    [Authorize(Roles = "authorized-user")]
    public class OrdersController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Orders
        public ActionResult Index(string sortOrder)
        {
            ViewBag.SortOrder = String.IsNullOrEmpty(sortOrder) ? "dateAsc" : sortOrder;
            var orders = from o in db.Orders select o;
            switch (sortOrder)
            {
                case "dateDesc":
                    orders = orders.OrderByDescending(o => o.DateCreated);
                    break;
                case "identifierDesc":
                    orders = orders.OrderByDescending(o => o.Identifier);
                    break;
                case "identifierAsc":
                    orders = orders.OrderBy(o => o.Identifier);
                    break;
                case "projectDesc":
                    orders = orders.OrderByDescending(o => o.Preproject);
                    break;
                case "projectAsc":
                    orders = orders.OrderBy(o => o.Preproject);
                    break;
                default:
                    orders = orders.OrderBy(o => o.DateCreated);
                    break;
            }
            return View(orders);
        }

        // GET: Orders/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = db.Orders.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            ViewBag.StepChanges = order.StepChanges.ToList();
            ViewBag.OrderProducts = db.OrderProducts.ToList().Where(op => op.Order.OrderId == order.OrderId);
            var stepQuery = from s in db.Steps select s;
            List<Step> steps = stepQuery.ToList();
            Dictionary<int, string> stepNames = new Dictionary<int, string>();
            foreach (Step s in steps)
                stepNames.Add(s.StepId, s.getDisplayName());
            ViewBag.StepNames = stepNames;
            ViewBag.OrderComments = order.OrderComments.ToList();
            return View(order);
        }

        // GET: Orders/Create
        [Authorize(Roles = "admin, management, sales-admin")]
        public ActionResult Create()
        {
            ViewBag.Clients = db.Clients.ToList();
            return View();
        }

        // POST: Orders/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin, management, sales-admin")]
        public ActionResult Create([Bind(Include = "OrderId,Identifier,Preproject,RequestDescription,Client")] Order order, int clientId)
        {
            if (ModelState.IsValid)
            {
                if(db.Orders.Select(o => o.Identifier).ToList().Contains(order.Identifier))
                {
                    ModelState.AddModelError("Identifier", "Ya existe una orden con ese identificador");
                    return View();
                }
                order.DateCreated = DateTime.Now;
                var steps = from s in db.Steps where s.Order == 1 select s;
                order.Step = steps.ToList().ElementAt(0);
                var clients = from s in db.Clients where s.ClientId == clientId select s;
                order.Client = clients.ToList().ElementAt(0);
                db.Orders.Add(order);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(order);
        }

        // GET: Orders/Edit/5
        [Authorize(Roles = "admin, management, sales-admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = db.Orders.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            ViewBag.Clients = db.Clients.ToList();
            ViewBag.Products = db.Products.ToList();
            ViewBag.OrderProducts = db.OrderProducts.ToList().Where(op => op.Order.OrderId == order.OrderId);
            return View(order);
        }

        // POST: Orders/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin, management, sales-admin")]
        public ActionResult Edit([Bind(Include = "OrderId,Identifier,Preproject,RequestDescription")] Order order, int clientId)
        {
            if (ModelState.IsValid)
            {
                //db.Entry(order).State = EntityState.Modified;
                Order toModify = db.Orders.Find(order.OrderId);
                toModify.Identifier = order.Identifier;
                toModify.Preproject = order.Preproject;
                toModify.RequestDescription = order.RequestDescription;
                var clients = from s in db.Clients where s.ClientId == clientId select s;
                toModify.Client = clients.ToList().ElementAt(0);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(order);
        }

        // GET: Orders/Delete/5
        [Authorize(Roles = "admin, management, sales-admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = db.Orders.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            return View(order);
        }

        // POST: Orders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin, management, sales-admin")]
        public ActionResult DeleteConfirmed(int id)
        {
            Order order = db.Orders.Find(id);
            db.Orders.Remove(order);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        [HttpPost]
        [Authorize(Roles = "admin, management, sales-admin")]
        public ActionResult AddOrderProduct(int orderId, int productId, string quantity)
        {
            int number = 0;
            Order order = db.Orders.Find(orderId);
            try
            {
                number = int.Parse(quantity);
                Product product = db.Products.Find(productId);
                OrderProduct orderProduct = new OrderProduct();
                orderProduct.Order = order;
                orderProduct.Product = product;
                orderProduct.Quantity = number;
                order.OrderProducts.Add(orderProduct);
                //db.OrderProducts.Add(orderProduct);
                db.SaveChanges();
            }
            catch
            {
                
            }
            ViewBag.Clients = db.Clients.ToList();
            ViewBag.Products = db.Products.ToList();
            ViewBag.OrderProducts = db.OrderProducts.ToList().Where(op => op.Order.OrderId == order.OrderId);
            return RedirectToAction("Edit", new { @id = order.OrderId });
        }

        [Authorize(Roles = "admin, management, sales-admin")]
        public ActionResult DeleteOrderProduct(int orderProductId)
        {
            OrderProduct orderProduct = db.OrderProducts.Find(orderProductId);
            int orderId = orderProduct.Order.OrderId;
            ViewBag.Clients = db.Clients.ToList();
            ViewBag.Products = db.Products.ToList();
            ViewBag.OrderProducts = db.OrderProducts.ToList().Where(op => op.Order.OrderId == orderId);
            db.OrderProducts.Remove(orderProduct);
            db.SaveChanges();
            return RedirectToAction("Edit", new { @id = orderId });
        }
    }
}

Net Project/Cotizaciones/Cotizaciones/Views/Orders/CommentPartial.cshtml
<td>
  
</td>

<table class="table-condensed">
    <tr>
        <th>Usuario</th>
        <th>Paso en proceso</th>
        <th>Fecha</th>
        <th>Comentario</th>
    </tr>
    @foreach (Cotizaciones.Models.OrderComment comment in ViewBag.OrderComments)
    {
        <tr>
            <td>@comment.User</td>
            <td>@ViewBag.StepNames[item.NextStepId]</td>
            <td>@item.User</td>
            <td>@item.DateChanged</td>
            <div class="row" style="margin-left:5px">
                @Html.Raw(string.Format("{0}-{1}: {2}", comment.Date, comment.User, comment.Comment));
            </div>
        </tr>
    }            
</table>

Net Project/Cotizaciones/Cotizaciones/Views/Orders/Create.cshtml
@model Cotizaciones.Models.Order

@{
    ViewBag.Title = "Nuevo Producto";
}

<div class="row">
    <div class="col-md-1" style="margin-top:20px;">
        @Html.ActionLink("Index", "Index", null, new { @class = "backButton" })
    </div>
    <div class="col-md-8">
        <h2>Nueva Orden</h2>
    </div>
</div>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Identifier, htmlAttributes: new { @class = "control-label col-md-2", @style = "color:red" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Identifier, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Identifier, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Preproject, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Preproject, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Preproject, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RequestDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RequestDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RequestDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">
                Cliente
            </label>
            <div class="col-md-10">
                <select name="clientId" id="clientId" class="form-control">
                    @foreach (Cotizaciones.Models.Client item in ViewBag.Clients)
                    {
                        <option value="@item.ClientId">@item.getFullName()</option>
                    }
                </select>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="btn btn-success" />
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Net Project/Cotizaciones/Cotizaciones/Views/Orders/Delete.cshtml
@model Cotizaciones.Models.Order

@{
    ViewBag.Title = "Eliminar";
}

<div class="row">
    <div class="col-md-1" style="margin-top:20px;">
        @Html.ActionLink("Index", "Index", null, new { @class = "backButton" })
    </div>
    <div class="col-md-8">
        <h2>Eliminar @string.Format("Orden {0}",Model.Identifier)</h2>
    </div>
</div>

<h3>¿Está seguro que desea eliminar esta ordén?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Identifier)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Identifier)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Preproject)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Preproject)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RequestDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RequestDescription)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Eliminar" class="btn btn-danger" />
        </div>
    }
</div>

Net Project/Cotizaciones/Cotizaciones/Views/Orders/Details.cshtml
@model Cotizaciones.Models.Order

@{
    ViewBag.Title = string.Format("Orden {0}",Model.Identifier);
}

<div class="row">
    <div class="col-md-1" style="margin-top:20px;">
        @Html.ActionLink("Index", "Index", null, new { @class = "backButton" })
    </div>
    <div class="col-md-6">
        <h2>@string.Format("Orden {0}",Model.Identifier)</h2>
    </div>
    <div class="col-md-4" style="float:right; margin-bottom: 5px; margin-top:15px;">
        @if (User.IsInRole("admin") || User.IsInRole("management") || User.IsInRole("sales-admin"))
        {
            @Html.ActionLink("PDF", "fromOrder", "PDF", new { orderId = Model.OrderId }, new { @class = "btn btn-success" })
        }
        @if (User.IsInRole("admin") || User.IsInRole("management") || User.IsInRole("sales-admin"))
        {
            @Html.ActionLink("Editar", "Edit", new { id = Model.OrderId }, new { @class = "btn btn-primary" })
        }
        @if (User.IsInRole("admin") || User.IsInRole("management") || User.IsInRole("sales-admin"))
        {
            @Html.ActionLink("Borrar", "Delete", new { id = Model.OrderId }, new { @class = "btn btn-danger" })
        }
    </div>
</div>

<div class="row">
    <hr />
    <div class="col-md-5">
        <h4>Detalles</h4>
        @Html.Partial("~/Views/Orders/DetailsPartial.cshtml", Model)
    </div>
    <div class="col-md-5">
        <h4>Productos</h4>
        @Html.Partial("~/Views/Orders/ProductsPartial.cshtml", Model)
    </div>
</div>

<div class="row">
    <hr />
    <h4>Historial de cambios</h4>
    <hr />
    @Html.Partial("~/Views/Orders/HistoryPartial.cshtml")
</div>

Net Project/Cotizaciones/Cotizaciones/Views/Orders/DetailsPartial.cshtml
@model Cotizaciones.Models.Order

<dl class="dl-horizontal">
    <dt>
        @Html.DisplayNameFor(model => model.Identifier)
    </dt>
    <dd>
        @Html.DisplayFor(model => model.Identifier)
    </dd>

    <dt>
        @Html.DisplayNameFor(model => model.Preproject)
    </dt>
    <dd>
        @Html.DisplayFor(model => model.Preproject)
    </dd>

    <dt>
        @Html.DisplayNameFor(model => model.DateCreated)
    </dt>
    <dd>
        @Html.DisplayFor(model => model.DateCreated)
    </dd>

    <dt>
        @Html.DisplayNameFor(model => model.Client)
    </dt>
    <dd>
        @if (Model.Client != null)
        {
            @Html.ActionLink(Model.Client.getFullName(), "Details", "Clients", new { @id = Model.Client.ClientId }, null);
        }
        else
        {
            @Html.Raw("No hay cliente definido")
        }
    </dd>

    <dt>
        @Html.DisplayNameFor(model => model.RequestDescription)
    </dt>
    <dd>
        @Html.DisplayFor(model => model.RequestDescription)
    </dd>

    <dt>
        Actualmente en el paso
    </dt>
    <dd>
        @Model.Step.getDisplayName()
    </dd>

</dl>

Net Project/Cotizaciones/Cotizaciones/Views/Orders/Edit.cshtml
@model Cotizaciones.Models.Order

@{
    ViewBag.Title = string.Format("Orden {0}", Model.Identifier);
}

<div class="row">
    <div class="col-md-1" style="margin-top:20px;">
        @Html.ActionLink("Index", "Index", null, new { @class = "backButton" })
    </div>
    <div class="col-md-8">
        <h2>@string.Format("Orden {0}", Model.Identifier)</h2>
    </div>
</div>

<div class="row">
    <hr />
    <div class="col-md-6">
        <h4>Orden</h4>
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
            <div class="form-horizontal">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.OrderId)

                <div class="form-group">
                    @Html.LabelFor(model => model.Identifier, htmlAttributes: new { @class = "control-label col-md-2", @style = "color:red" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Identifier, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Identifier, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Preproject, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Preproject, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Preproject, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.RequestDescription, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.RequestDescription, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.RequestDescription, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-md-2">
                        Cliente
                    </label>
                    <div class="col-md-10">

                        <select name="clientId" id="clientId" class="form-control">
                            @foreach (Cotizaciones.Models.Client item in ViewBag.Clients)
                            {
                                if (Model.Client.ClientId == item.ClientId)
                                {
                                    <option value="@item.ClientId" selected="selected">@item.getFullName()</option>
                                }
                                else
                                {
                                    <option value="@item.ClientId">@item.getFullName()</option>
                                }
                            }
                        </select>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Guardar" class="btn btn-success" />
                    </div>
                </div>
            </div>
        }
    </div>
    <div class="col-md-6">
        <h4>Productos</h4>
        <table class="table-condensed">
            <tr>
                <th>Fabricante</th>
                <th>Producto</th>
                <th>Cantidad</th>
                <th></th>
            </tr>
            @foreach (Cotizaciones.Models.OrderProduct item in ViewBag.OrderProducts)
            {
            <tr>
                    <td>@item.Product.Provider</td>
                    <td>@item.Product.Name</td>
                    <td>@item.Quantity</td>
                    <td>@Html.ActionLink("Quitar", "DeleteOrderProduct", new { @orderProductId = item.OrderProductId }, new { @style = "color:red"})</td>
                
            </tr>
            }
            <tr>
                @if(ViewBag.Products != null && ViewBag.Products.Count != 0)
                { 
                    using (Html.BeginForm("AddOrderProduct", "Orders"))
                    {
                        <td></td>
                        <td>
                            <input type="text" hidden="hidden" value="@Model.OrderId" name="orderId" id="orderId" />
                            <select name="productId" id="productId" class="form-control">
                                @foreach (Cotizaciones.Models.Product item in ViewBag.Products)
                                {
                                    <option value="@item.ProductId">@item.Name</option>
                                }
                            </select>
                        </td>
                        <td>
                            <input type="text" name="quantity" id="quantity" placeholder="0" class="form-control" />
                        </td>
                        <td>
                            <input type="submit" value="Agregar" class="btn btn-success" />
                        </td>
                    }
                }
            </tr>

        </table>
    </div>
</div>

        @section Scripts {
            @Scripts.Render("~/bundles/jqueryval")
        }

Net Project/Cotizaciones/Cotizaciones/Views/Orders/HistoryPartial.cshtml
<table class="table-condensed">
    <tr>
        <th>Paso anterior</th>
        <th>Paso siguiente</th>
        <th>Usuario</th>
        <th>Fecha</th>
        <th>Comentarios</th>
    </tr>
    @foreach (Cotizaciones.Models.StepChange item in ViewBag.StepChanges)
    {
        <tr>
            <td>@ViewBag.StepNames[item.PreviousStepId]</td>
            <td>@ViewBag.StepNames[item.NextStepId]</td>
            <td>@item.User</td>
            <td>@item.DateChanged</td>
            <td >
                @foreach (Cotizaciones.Models.OrderComment comment in ViewBag.OrderComments)
                {
                    if(comment.Step.StepId.Equals(item.PreviousStepId))
                    { 
                        <div class="row" style="margin-left:5px">
                            @Html.Raw(string.Format("{0}-{1}: {2}", comment.Date, comment.User, comment.Comment))
                        </div>
                    }
                }
            </td>
        </tr>
    }
</table>

Net Project/Cotizaciones/Cotizaciones/Views/Orders/ProductsPartial.cshtml
@model Cotizaciones.Models.Order

<table class="table-condensed">
    <tr>
        <th>Fabricante</th>
        <th>Producto</th>
        <th>Cantidad</th>
    </tr>
    @foreach (Cotizaciones.Models.OrderProduct item in ViewBag.OrderProducts)
    {
        <tr>
            <td>@item.Product.Provider</td>
            <td>@Html.ActionLink(item.Product.Name, "Details", "Products", new { @id = item.Product.ProductId }, null)</td>
            <td>@item.Quantity</td>
        </tr>
    }
</table>